# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  agenda:
    build: ./src/
    image: gabcas28/mobility-agenda
    depends_on:
      - db
    command:  bash -c "invoke install && invoke start"    
    volumes:
      - ./src:/src
    ports:
      - 8000:8000