version: '3.2'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
       - ./.env
  agenda:
    build: ./src/
    image: gabcas28/mobility-agenda
    restart: always
    depends_on:
      - db
    command:  bash -c " invoke install && invoke start"    
    volumes:
      - ./src:/src
    ports:
      - 8000:8000
    env_file:
      - ./.env
volumes:
  postgres: